### ISSUE TITLE
FATAL:  remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by drnextgis** [sacrud/pyramid_sacrud#121]
DB is located on `localhost` and I'm only one user there.
```
2016-05-04 08:29:43,412 INFO  [sqlalchemy.engine.base.Engine:646][waitress] BEGIN (implicit)
2016-05-04 08:29:43,412 INFO  [sqlalchemy.engine.base.Engine:1097][waitress] SELECT organization.id AS organization_id, organization.name AS organization_name 
FROM organization 
WHERE organization.id = %(id_1)s
2016-05-04 08:29:43,413 INFO  [sqlalchemy.engine.base.Engine:1100][waitress] {'id_1': '9'}
2016-05-04 08:29:43,414 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,415 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,415 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,415 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,416 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,416 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,416 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,417 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,417 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:43,417 INFO  [sqlalchemy.engine.base.Engine:666][waitress] ROLLBACK
2016-05-04 08:29:46,311 ERROR [pyramid_debugtoolbar:227][waitress] Exception at http://localhost:6543/admin/Sportsmans/organization/?page=3
traceback url: http://localhost:6543/_debug_toolbar/exception?token=b06a228d3cec7ed8dd73&tb=139638725085968
Traceback (most recent call last):
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 209, in toolbar_tween
    response = _handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 497, in _class_view
    response = getattr(inst, attr)()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/ps_alchemy/views.py", line 91, in list_view
    'paginator': SqlalchemyOrmPage(rows, **paginator_attr)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/paginate_sqlalchemy/__init__.py", line 35, in __init__
    super(SqlalchemyOrmPage, self).__init__(*args, wrapper_class=SqlalchemyOrmWrapper, **kwargs)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/paginate/__init__.py", line 251, in __init__
    self.items = list(self.collection[first:last])
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/paginate_sqlalchemy/__init__.py", line 20, in __getitem__
    return self.obj[range]
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in _execute_and_instances
    close_with_result=True)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2740, in _connection_from_session
    **kw)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/rykov/git/sport_venue/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

I see that after each web GUI interaction the number of database connections increases until it reaches a limit.

**Comment by uralbash** [comment]
Merged. Thanks!
